Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 140

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Max: 35

Metrics/ClassLength:
  Max: 250

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Style/ClassVars:
  Enabled: false